# Generated by Django 2.2 on 2021-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='regular_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
