# Generated by Django 2.2 on 2021-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210225_1426'),
        ('category', '0002_auto_20210223_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
