# Generated by Django 2.2 on 2021-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210312_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
